name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/user_application_ui/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/user_application_ui/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/user_application_ui
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/user_application_ui/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Format check
        run: npx prettier --check 'src/**/*.{vue,js,jsx,ts,tsx,css,md}'
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/user_application_ui
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/user_application_ui/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
